print('''
        \______________@@@@@@@@@@@@@@@@@@@@________________\
    `   \@@@@@@@@@@@THE NUCLEAR MISSILE LAUNCHER@@@@@@@@@@@@@\
        \_____________________________________________________\
        \________________CREATED BY MOHD ATIF_________________|
        \_____________________________________________________/
        \---------------------------------------------------/
         
         ''')
print("Welcome to The Space War Game")
print("You are mission is to protect your Earth from Asteroid")

choice_1 = input("We are in the Spaceship! Where do you want to go? 'Out' or 'Back to Earth' ")

choice_2 = input("We are in the Out of Spaceship. there is a nuclear missile launcher on the Moon to fight with this Asteroid."
                 "\n 'Fight' and Second is 'GoBack' ")

if choice_1 == 'Out':
    print("Congratulations You Win protect earth from asteroid")
elif choice_2 == 'Fight':
    print('Daring: You save the earth from asteroid!')
else:
    print("Game Over: Asteroid hit the Planet")
